baseURL: https://JoboPortfolio/
languageCode: es-mx
build:
  writeStats: true
params:
  title: Jacob CV
  author: Jobo
  description: Título del sitio web
  copyright: >-
    powered by [hugo](https://gohugo.io/) & desplegado en
    [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Jacob de Jesús Angel Villanueva."
    tagline: Desarrollador de software Junior
    location: 
    photo: Jobo-foto-cv.jpg
  social:
    title: Enlaces
    list:
      - icon: fab fa-linkedin-in
        url: "www.linkedin.com/in/jacob-dejesús-angel-villanueva-8aba8b201"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/joboxd"
        title: GitHub
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: Acerca de mí
    icon: fas fa-user
    description: Me especializo en tecnologías como JavaScript, HTML, CSS y frameworks como [Angular](https://angular.dev/), [React](https://es.react.dev/) y [Spring Boot.](https://spring.io/projects/spring-boot) Me apasiona resolver problemas complejos y aprender continuamente nuevas herramientas y lenguajes. Me enfoco en la calidad del código, el trabajo en equipo y la mejora continua. Estoy buscando oportunidades para seguir desarrollando mis habilidades y contribuir a proyectos innovadores.
  experience:
    title: Experiencia
    icon: fas fa-briefcase
    list:
      - position: Desarrollador Junior
        dates: 2023 - *Presente*
        url: https://www.tecnomotum.com.mx/
        company: TECNOMOTUM
        details: |1-
          - Recolección de requerimientos con usuarios
          - Mejorar procesos existentes de otras áreas mediante desarrollo de software especializado en sus necesidades
          - Mentoreo de otros miembros del equipo
          - Despliegue de aplicaciones backend y frontend
          - Creación de consultas para bases de datos relacionales y no relacionales
          - Creación de diagramas UML relacionales
          - Migración de repositorios GitHub
          - [Aplicaciones sin código (Appsheet)](https://about.appsheet.com/home/)
      - position: Practicante en PMO
        dates: 2022 - 2023
        url: "https://www.tenaristamsa.com/es"
        company: TENARIS TAMSA
        details: |1-
          - Creación y soporte para Macros en Excel
          - Mentoreo a otros miembros del equipo sobre cómo desarrollar Macros
          - Proceso diario de actualización de archivos de clientes
          - Mejorar procesos existentes
          - Optimización de tiempos de carga, descarga y actualización de documentos
          - [Aplicaciones sin código (PowerApps)](https://www.microsoft.com/es-es/power-platform/products/power-apps)
  education:
    title: Educación
    icon: fas fa-graduation-cap
    list:
      - degree: Ingeniería en Sistemas Computacionales
        college: Instituto Tecnológico de Orizaba
        dates: 2017 - 2022
  
  project:
    title: Proyectos
    icon: fas fa-project-diagram
    list:
    - title: Integraciones de Netsuite
      description: Creación de ETLs para conectar Netsuite con otras plataformas de Motum (Java)
    - title: Gestión de Inventario TI
      description: Gestión de activos de TI – Soporte en AppSheet
    - title: Cálculo de Comisiones ST
      description: Sistema complejo para gestionar las comisiones de soporte técnico (Angular/Java/MySQL)
    - title: Sistema Qualitas
      description: Sistema para mostrar los detalles de suscripción de Qualitas (ReactJS/Java/PostgreSQL)
    - title: Enviar Facturas
      description: Aplicación Java para enviar facturas a clientes desde archivos de Excel
    - title: Enviar Tiempos de Actividad (Uptime)
      description: Aplicación Java para enviar resúmenes de tickets a los clientes de Motum utilizando dos archivos Excel para el departamento de CSM
  skill:
    title: Habilidades
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "- Angular"
      - skill: "- ReactJS"
      - skill: "- SpringBoot"
      - skill: "- Docker"
      - skill: "- GCP (Artifact Registry, CloudRun, Jobs, Firebase, Firestore)"
      - skill: "- Git, GitHub, GitLab"
      - skill: "- SQL, MYSQL, POSTGRESQL"
      - skill: "- JIRA"
      - skill: "- Appsheet"
      - skill: "- Inglés B1+"
  hobby:
    title: En progreso
    icon: fas fa-code
    list: 
      - hobby: "- DevOps"
      - hobby: "- Jenkins"
      - hobby: "- CI/CD"
      - hobby: "- AWS"
