baseURL: https://JoboPortfolio/
languageCode: en-us
build:
  writeStats: true
params:
  title: Jacob CV
  author: Jobo
  description: Website title
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Jacob de Jesús Angel Villanueva."
    tagline: Software developer Junior
    location: 
    photo: Jobo-foto-cv.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "www.linkedin.com/in/jacob-dejesús-angel-villanueva-8aba8b201"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/joboxd"
        title: GitHub
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: I specialize in technologies such as JavaScript, HTML, CSS, and frameworks like [Angular](https://angular.dev/), [React](https://es.react.dev/), and [Spring Boot.](https://spring.io/projects/spring-boot) I am passionate about solving complex problems and continuously learning new tools and languages. I focus on code quality, teamwork, and continuous improvement. I am looking for opportunities to further develop my skills and contribute to innovative projects. 
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Junior Developer
        dates: 2023 - *Present*
        url: https://www.tecnomotum.com.mx/
        company: TECNOMOTUM
        details: |1-
          - Requirement gathering with users
          - Improving existing processes from other areas through software development specialized in their needs
          - Mentoring other team members
          - Deployment of backend and frontend applications
          - Creating queries for relational and non-relational databases
          - Creating relational UML diagrams
          - Migrating GitHub repositories
          - [Nocode Apps (Appsheet)](https://about.appsheet.com/home/)
      - position: PMO Trainee
        dates: 2022 - 2023
        url: "https://www.tenaristamsa.com/es"
        company: TENARIS TAMSA
        details: |1-
          - Creation and support to Excel Macros
          - Mentoring other team members about how to dev Macros
          - Daily proccess to update the Customers' files
          - Improving existing processes
          - Optimization of loading, unloading, and updating times for documents
          - [NocodeApps (PowerApps)](https://www.microsoft.com/es-es/power-platform/products/power-apps)
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Bachelor's Degree in Computer Systems Engineering
        college: Instituto Tecnologico de Orizaba
        dates: 2017 - 2022
  
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
    - title: Netsuite Integrations
      description: Creation of ETLs to connect Netsuite with other Motum platforms (Java)
    - title: Inventory Management
      description: Management of IT assets – Support in AppSheet
    - title: Calculate Commissions ST
      description: Complex system to manage technical support commissions (Angular/Java/MySQL)
    - title: Qualitas System
      description: System to display Qualitas subscription details (ReactJS/Java/PostgreSQL)
    - title: Send Invoices
      description: Java application to send invoices to customers from Excel files
    - title: Send Uptime
      description: Java application to send ticket summaries to Motum’s customers using two Excel files for the CSM department

  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "- Angular"
      - skill: "- ReactJS"
      - skill: "- SpringBoot"
      - skill: "- Docker"
      - skill: "- GCP(Artifact Registry, CloudRun, Jobs, Firebase, Firestore)"
      - skill: "- Git, GitHub, GitLab"
      - skill: "- SQL, MYSQL, POSTGRESQL"
      - skill: "- JIRA"
      - skill: "- Appsheet"
      - skill: "- English B1+"
  hobby:
    title: In progress
    icon: fas fa-code
    list: 
      - hobby: "- DevOps"
      - hobby: "- Jenkins"
      - hobby: "- CI/CD"
      - hobby: "- AWS"
